{
  "metadata": {
    "timestamp": "2025-02-23T12:17:24Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2019-16935",
        "description": "The documentation XML-RPC server in Python through 2.7.16, 3.x through 3.6.9, and 3.7.x through 3.7.4 has XSS via the server_title field. This occurs in Lib/DocXMLRPCServer.py in Python 2.x, and in Lib/xmlrpc/server.py in Python 3.x. If set_server_title is called with untrusted input, arbitrary JavaScript can be delivered to clients that visit the http URL for this server.",
        "metadata": {
          "published_date": "2019-09-28T02:15:10.463",
          "last_modified_date": "2024-11-21T04:31:23.140",
          "confidence_level": "medium",
          "severity": "medium"
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": false
        },
        "counts": {
          "public_exploit_count": 2
        },
        "epss": {
          "score": 0.00303,
          "percentile": 0.69671
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            "attack_vector": "NETWORK",
            "base_score": 6.09999990463257
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
            "attack_vector": "NETWORK",
            "base_score": 4.30000019073486
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue38243",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2019-09-28T05:00:00.000Z"
            },
            {
              "type": "reference",
              "url": "https://bugs.python.org/issue38243",
              "source_type": "poc",
              "source": "nvd",
              "description": "",
              "published": "2019-09-28T05:00:00.000Z"
            }
          ],
          "repositories": []
        }
      }
    }
  ]
}