{
  "metadata": {
    "timestamp": "2025-02-26T22:10:29Z"
  },
  "data": [
    {
      "cve": {
        "id": "CVE-2022-29885",
        "description": "The documentation of Apache Tomcat 10.1.0-M1 to 10.1.0-M14, 10.0.0-M1 to 10.0.20, 9.0.13 to 9.0.62 and 8.5.38 to 8.5.78 for the EncryptInterceptor incorrectly stated it enabled Tomcat clustering to run over an untrusted network. This was not correct. While the EncryptInterceptor does provide confidentiality and integrity protection, it does not protect against all risks associated with running over any untrusted network, particularly DoS risks.",
        "metadata": {
          "published": "",
          "last_modified": "",
          "confidence_level": "medium",
          "severity": "high",
          "source": "",
          "status": ""
        },
        "impact": {
          "cisa_kev": false,
          "reported_exploited": false,
          "exploit_maturity": "poc",
          "automatable": true
        },
        "metrics": [
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "3.1",
            "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "attack_vector": "NETWORK",
            "base_score": 7.5
          },
          {
            "source": "nvd@nist.gov",
            "type": "Primary",
            "cvss_version": "2.0",
            "vector_string": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "attack_vector": "NETWORK",
            "base_score": 5
          }
        ],
        "timeline": {
          "references": [
            {
              "type": "reference",
              "url": "https://packetstormsecurity.com/files/download/171728/apachetomcat101-dos.txt",
              "source_type": "poc",
              "source": "packetstorm",
              "description": "Apache Tomcat 10.1 Denial Of Service",
              "published": "2023-04-06T05:00:00.000Z"
            },
            {
              "type": "reference",
              "url": "https://gitlab.com/exploit-database/exploitdb/-/blob/main/exploits/multiple/dos/51262.py",
              "source_type": "poc",
              "source": "exploitdb",
              "description": "Apache Tomcat 10.1 - Denial Of Service",
              "published": "2023-04-05T05:00:00.000Z"
            }
          ],
          "repositories": [
            {
              "type": "repository",
              "url": "https://github.com/quynhlab/CVE-2022-29885",
              "description": "Apache Tomcat CVE-2022-29885",
              "published": "2022-06-30T13:46:47Z",
              "created": "2022-06-30T16:09:25Z",
              "last_modified": "2024-11-16T19:54:21Z",
              "repo_name": "quynhlab/CVE-2022-29885",
              "name": "",
              "stars": 5,
              "forks": 4
            },
            {
              "type": "repository",
              "url": "https://github.com/iveresk/CVE-2022-29885",
              "description": "Apache Tomcat DoS (CVE-2022-29885) Exploit",
              "published": "2022-07-05T06:23:18Z",
              "created": "2022-07-01T09:02:10Z",
              "last_modified": "2024-04-29T08:54:03Z",
              "repo_name": "iveresk/CVE-2022-29885",
              "name": "",
              "stars": 4,
              "forks": 2
            }
          ]
        },
        "epss": {
          "score": 0.08539,
          "percentile": 0.94557
        },
        "counts": {
          "public_exploit_count": 4
        }
      }
    }
  ]
}